document.querySelector(".accounts").before(document.querySelector(".gallery"));
document.head.insertAdjacentHTML(
  "beforeend",
  "<style>.gallery{background:#fbfaf8}.accounts{background:#fff}footer button{display:block;margin:20px auto 0;padding:9px 13px;border:1px dashed #999;background:#fff;color:#555;font:10px Space Mono,monospace;cursor:pointer}</style>",
);
const NAVER_MAP_CLIENT_ID="YOUR_NAVER_MAP_CLIENT_ID";
const weddingDate=new Date("2027-09-26T11:00:00+09:00");function countdown(){const x=Math.max(0,weddingDate-new Date()),d=Math.floor(x/86400000),h=Math.floor(x/36e5)%24,m=Math.floor(x/6e4)%60,s=Math.floor(x/1000)%60;[["days",d,3],["hours",h,2],["minutes",m,2],["seconds",s,2]].forEach(([id,n,l])=>document.querySelector(`#${id}`).textContent=String(n).padStart(l,"0"));document.querySelector("#dday-text").textContent=d}countdown();setInterval(countdown,1000);
function initMap(){const p=new naver.maps.LatLng(37.5166,127.0208),map=new naver.maps.Map("naver-map",{center:p,zoom:16,zoomControl:true});new naver.maps.Marker({position:p,map,title:"더컨벤션 신사"})}if(NAVER_MAP_CLIENT_ID!=="YOUR_NAVER_MAP_CLIENT_ID"){window.initMap=initMap;const s=document.createElement("script");s.src=`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${encodeURIComponent(NAVER_MAP_CLIENT_ID)}&callback=initMap`;document.head.append(s)}
const toast=document.querySelector("#toast");function notice(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}document.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",async()=>{await navigator.clipboard.writeText(b.dataset.copy);notice("계좌번호를 복사했습니다.")}));document.querySelector("#copy-url").addEventListener("click",async()=>{await navigator.clipboard.writeText(location.href);notice("청첩장 주소를 복사했습니다.")});document.querySelector("#share").addEventListener("click",()=>navigator.share?navigator.share({title:"한신랑 · 김신부 결혼식",url:location.href}):notice("공유 기능을 지원하지 않습니다."));
const terminal=document.querySelector("#terminal"),out=document.querySelector("#terminal-output"),pages=["$ ./wedding-invitation --open\n\nInitializing love_protocol...\n[████████████████████] 100%\n\nACCESS GRANTED\n","\n  ♥  한신랑  +  김신부  ♥\n\n2027. 09. 26. SUN 11:00\nTHE CONVENTION SINSA\n\n새로운 챕터의 시작에\n함께 접속해 주세요.\n","\n$ location --open\n더컨벤션 신사\n\nSee you at our happiest commit.\n"];let pg=0,timer;function type(){clearInterval(timer);out.textContent="";let i=0;timer=setInterval(()=>{out.textContent+=pages[pg][i++]||"";if(i>=pages[pg].length)clearInterval(timer)},16)}function next(){pg=(pg+1)%pages.length;type()}document.querySelector("#open-terminal").onclick=()=>{terminal.classList.add("is-open");pg=0;type()};document.querySelector("#close-terminal").onclick=()=>terminal.classList.remove("is-open");document.querySelector("#terminal-next").onclick=next;document.addEventListener("keydown",e=>{if(terminal.classList.contains("is-open")){if(e.key==="Escape")terminal.classList.remove("is-open");if(e.key==="Enter")next()}});
